-- Encyclopedia Table
CREATE TABLE IF NOT EXISTS encyclopedia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    content TEXT[] -- Array of text for paragraphs
);

-- Tournaments Table
CREATE TABLE IF NOT EXISTS tournaments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    format TEXT NOT NULL,
    location TEXT,
    is_online BOOLEAN DEFAULT FALSE,
    organizer TEXT,
    contact TEXT
);

-- Motions Table
CREATE TABLE IF NOT EXISTS motions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    topic TEXT NOT NULL,
    type TEXT NOT NULL,
    difficulty TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE encyclopedia ENABLE ROW LEVEL SECURITY;
ALTER TABLE tournaments ENABLE ROW LEVEL SECURITY;
ALTER TABLE motions ENABLE ROW LEVEL SECURITY;

-- Policies (Example: Public Read, Authenticated Write)
-- Note: Adjust based on your actual Clerk/Supabase Auth setup.

-- Allow public read access (or restricted based on app logic)
CREATE POLICY "Allow public read access" ON encyclopedia FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON tournaments FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON motions FOR SELECT USING (true);

-- Allow authenticated users to insert (if needed)
-- CREATE POLICY "Allow authenticated insert" ON tournaments FOR INSERT WITH CHECK (auth.role() = 'authenticated');
